[core]
hostname = "mark"
timezone = "America/New_York"
kernels = ["linux"]
ntp = true

[locale]
language = "en_US.UTF-8"
encoding = "UTF-8"
keyboard = "us"

[boot]
loader = "systemd-boot"

[[disk]]
device = "/dev/nvme0n1"
wipe = true
table = "gpt"

  [[disk.partition]]
  mount   = "/boot"
  fs      = "fat32"
  size    = "512MiB"
  start   = "1MiB"
  flags   = ["boot", "esp"]

  [[disk.partition]]
  mount   = "/"
  fs      = "btrfs"
  size    = "rest"
  encrypt = true             # LUKS; password comes from creds file
  subvolumes = [
    { name = "@",       mount = "/" },
    { name = "@home",   mount = "/home" },
    { name = "@log",    mount = "/var/log" },
    { name = "@pkgs",   mount = "/var/cache/pacman/pkg" },
  ]
  mount-options = ["compress=zstd", "noatime"]

[swap]
enabled = true
algorithm = "zstd"

[[user]]
name = "spader"
sudo = true
groups = ["wheel"]

[packages]
extra = [ "git", "neovim" ]
services = ["sshd"]

[repositories]
multilib = true
testing = true

  [[repositories.custom]]
  name = "myrepo"
  url = "https://myrepo.example.com/$repo/os/$arch"
  sign-check = "Required"              # Never | Optional | Required
  sign-option = "TrustedOnly"           # TrustedOnly | TrustAll

[mirrors]
regions = ["United States", "Canada"]
custom  = ["https://mymirror.example.com/$repo/os/$arch"]

[network]
mode = "networkmanager" # iwd, iso, manual, none

# For manual:

# [[network.nic]]
# interface = "eno1"
# dhcp      = false
# ip        = "192.168.1.15/24"
# gateway   = "192.168.1.1"
# dns       = ["1.1.1.1", "9.9.9.9"]

[profile]
type        = "desktop"          # desktop | minimal | server | xorg | custom
flavor      = "KDE Plasma"       # gnome | sway | i3-wm | xfce4 | ...
gfx-driver  = "amd"              # intel | amd | nvidia-open | nouveau | nvidia | virtualbox | all-open
greeter     = "sddm"             # sddm | gdm | lightdm

[apps]
audio            = "pipewire"     # pipewire | pulseaudio | none
bluetooth        = true
printing         = false
firewall         = "ufw"          # ufw | firewalld | none
power-management = "tuned"        # power-profiles-daemon | tuned | none
fonts = ["noto-fonts", "noto-fonts-emoji", "ttf-liberation"]
