[core]
hostname = "mark"
timezone = "UTC"
kernels = ["linux"]
ntp = true

[locale]
language = "en_US.UTF-8"
encoding = "UTF-8"
keyboard = "us"

[boot]
loader = "systemd-boot"
uki = true

[[disk]]
device = "/dev/vda"
wipe = true
table = "gpt"

  [[disk.partition]]
  mount = "/boot"
  fs    = "fat32"
  size  = "512MiB"
  start = "1MiB"
  flags = ["boot", "esp"]

  [[disk.partition]]
  mount = "/"
  fs    = "ext4"
  size  = "rest"

[swap]
enabled = true

[[user]]
name = "spader"
sudo = true
groups = ["wheel"]

[packages]
extra = [ "git", "vim" ]
services = ["sshd"]

[pacman.mirrors]
regions = ["United States"]

[network]
mode = "iso"

