import fs from "fs";
import { test, expect } from "bun:test";
import { ignore } from "@bicycle/shared";
import { useSandbox } from "../testing";
import { paths } from "../paths";
import * as ignorefile from "../ignorefile";
import { formatEntries, parseAconfmgr, coveredByDefaults, runImport } from "./ignore";

useSandbox();

type ParseCase = {
  name: string;
  script: string;
  expect: {
    entries: ignorefile.Entry[];
    warnings?: string[];
  };
};

const PARSE_CASES: ParseCase[] = [
  {
    name: "trailing /* becomes a whole-subtree **",
    script: "IgnorePath '/var/*'\n",
    expect: { entries: [{ section: "files", value: "/var/**" }] },
  },
  {
    name: "bare suffix glob stays unanchored",
    script: "IgnorePath '*.pacnew'\n",
    expect: { entries: [{ section: "files", value: "*.pacnew" }] },
  },
  {
    name: "trailing * after a non-slash still crosses",
    script: "IgnorePath '/etc/ssh/ssh_host_*'\n",
    expect: { entries: [{ section: "files", value: "/etc/ssh/ssh_host_**" }] },
  },
  {
    name: "escaped spaces inside single quotes unescape",
    script: "IgnorePath '/etc/NetworkManager/system-connections/Wired\\ connection\\ 1.nmconnection'\n",
    expect: {
      entries: [
        {
          section: "files",
          value: "/etc/NetworkManager/system-connections/Wired connection 1.nmconnection",
        },
      ],
    },
  },
  {
    name: "escaped spaces in an unquoted pattern",
    script: "IgnorePath /etc/Wired\\ connection\n",
    expect: { entries: [{ section: "files", value: "/etc/Wired connection" }] },
  },
  {
    name: "unquoted exact path",
    script: "IgnorePath /etc/udev/rules.d\n",
    expect: { entries: [{ section: "files", value: "/etc/udev/rules.d" }] },
  },
  {
    name: "IgnorePackage drops --foreign",
    script: "IgnorePackage --foreign neofetch\n",
    expect: { entries: [{ section: "packages", value: "neofetch" }] },
  },
  {
    name: "IgnoreFile is an exact files entry",
    script: "IgnoreFile /etc/group\n",
    expect: { entries: [{ section: "files", value: "/etc/group" }] },
  },
  {
    name: "interior * imports as-is with a warning",
    script: "IgnorePath '/usr/share/icons/*/icon-theme.cache'\n",
    expect: {
      entries: [{ section: "files", value: "/usr/share/icons/*/icon-theme.cache" }],
      warnings: ['interior "*"'],
    },
  },
  {
    name: "interior and trailing * combine",
    script: "IgnorePath '/usr/lib/ghc-*/lib/package.conf.d/*'\n",
    expect: {
      entries: [{ section: "files", value: "/usr/lib/ghc-*/lib/package.conf.d/**" }],
      warnings: ['interior "*"'],
    },
  },
  {
    name: "comments and blank lines are skipped",
    script: "# Caches regenerated by hooks\n\n  # indented comment\n",
    expect: { entries: [] },
  },
  {
    name: "unknown directives warn and are skipped",
    script: "AddPackage vim\n",
    expect: { entries: [], warnings: ["unknown directive"] },
  },
  {
    name: "missing argument warns",
    script: "IgnorePath\n",
    expect: { entries: [], warnings: ["missing pattern"] },
  },
  {
    name: "mixed script keeps order",
    script: [
      "IgnorePath '/swapfile'",
      "# systemd enablement",
      "IgnorePath '/etc/systemd/user/*'",
      "IgnorePackage --foreign yay-debug",
      "IgnoreFile /etc/passwd",
    ].join("\n"),
    expect: {
      entries: [
        { section: "files", value: "/swapfile" },
        { section: "files", value: "/etc/systemd/user/**" },
        { section: "packages", value: "yay-debug" },
        { section: "files", value: "/etc/passwd" },
      ],
    },
  },
];

for (const c of PARSE_CASES) {
  test(`parseAconfmgr: ${c.name}`, () => {
    const got = parseAconfmgr(c.script);
    expect(got.entries).toEqual(c.expect.entries);
    const want = c.expect.warnings ?? [];
    expect(got.warnings).toHaveLength(want.length);
    for (let i = 0; i < want.length; i++) expect(got.warnings[i]).toContain(want[i]!);
  });
}

type AddCase = {
  name: string;
  before?: string;
  adds: { entry: ignorefile.Entry; added: boolean }[];
  expect: { contains: string[] };
};

const ADD_CASES: AddCase[] = [
  {
    name: "first add creates ignore.yml",
    adds: [{ entry: { section: "packages", value: "neofetch" }, added: true }],
    expect: { contains: ["packages:", "neofetch"] },
  },
  {
    name: "identical entry reports already present",
    adds: [
      { entry: { section: "files", value: "/opt/junk" }, added: true },
      { entry: { section: "files", value: "/opt/junk" }, added: false },
    ],
    expect: { contains: ["files:", "/opt/junk"] },
  },
  {
    name: "field rules land in diffs",
    adds: [
      {
        entry: { section: "diffs", value: { type: "file", id: "/etc/motd", field: "mode" } },
        added: true,
      },
    ],
    expect: { contains: ["diffs:", "type: file", "id: /etc/motd", "field: mode"] },
  },
  {
    name: "comments in an existing file survive",
    before: "# judged noise\nfiles: [/swapfile]\n",
    adds: [{ entry: { section: "units", value: "foo.service" }, added: true }],
    expect: { contains: ["# judged noise", "/swapfile", "foo.service"] },
  },
];

const runAddCase = (c: AddCase) => {
  if (c.before !== undefined) fs.writeFileSync(paths.etc.ignoreYaml, c.before);
  for (const a of c.adds) {
    expect(ignorefile.add(a.entry)).toBe(a.added);
  }
  const text = fs.readFileSync(paths.etc.ignoreYaml, "utf8");
  for (const s of c.expect.contains) expect(text).toContain(s);
};

for (const c of ADD_CASES) {
  test(`add: ${c.name}`, () => runAddCase(c));
}

type LsCase = {
  name: string;
  yml?: string;
  builtin?: boolean;
  expect: { lines?: string[]; contains?: string[] };
};

const LS_CASES: LsCase[] = [
  {
    name: "empty file lists nothing",
    expect: { lines: [] },
  },
  {
    name: "entries print one per line, prefixed by section",
    yml: [
      "files: [/var/**, '*.pacnew']",
      "packages: [neofetch]",
      "units: [foo.service]",
      "diffs:",
      "  - { type: file, id: /etc/motd, field: mode }",
      "  - { type: package, id: bar }",
    ].join("\n"),
    expect: {
      lines: [
        "files /var/**",
        "files *.pacnew",
        "packages neofetch",
        "units foo.service",
        "diffs file /etc/motd mode",
        "diffs package bar",
      ],
    },
  },
  {
    name: "--builtin shows the shipped baseline",
    builtin: true,
    expect: { contains: ["files /dev/**", "files /etc/machine-id", "files *.pacnew"] },
  },
];

const runLsCase = (c: LsCase) => {
  if (c.yml !== undefined) fs.writeFileSync(paths.etc.ignoreYaml, c.yml);
  const cfg = c.builtin ? ignore.DEFAULTS : ignorefile.read().cfg;
  const lines = formatEntries(cfg);
  if (c.expect.lines) expect(lines).toEqual(c.expect.lines);
  for (const s of c.expect.contains ?? []) expect(lines).toContain(s);
};

for (const c of LS_CASES) {
  test(`ls: ${c.name}`, () => runLsCase(c));
}

type CoveredCase = { name: string; entry: ignorefile.Entry; expect: boolean };

const COVERED_CASES: CoveredCase[] = [
  {
    name: "exact path shipped verbatim",
    entry: { section: "files", value: "/etc/machine-id" },
    expect: true,
  },
  {
    name: "exact path under a shipped prune",
    entry: { section: "files", value: "/var/log/pacman.log" },
    expect: true,
  },
  {
    name: "glob shipped verbatim",
    entry: { section: "files", value: "*.pacnew" },
    expect: true,
  },
  {
    name: "glob with interior * shipped verbatim",
    entry: { section: "files", value: "/usr/share/icons/*/icon-theme.cache" },
    expect: true,
  },
  {
    name: "novel exact path is not covered",
    entry: { section: "files", value: "/swapfile" },
    expect: false,
  },
  {
    name: "novel glob is not probed",
    entry: { section: "files", value: "/boot/EFI/Linux/**" },
    expect: false,
  },
  {
    name: "packages are never in the baseline",
    entry: { section: "packages", value: "neofetch" },
    expect: false,
  },
  {
    name: "diffs rules are never covered",
    entry: { section: "diffs", value: { type: "file", id: "/etc/machine-id" } },
    expect: false,
  },
];

for (const c of COVERED_CASES) {
  test(`coveredByDefaults: ${c.name}`, () => {
    expect(coveredByDefaults(c.entry)).toBe(c.expect);
  });
}

type ImportCase = {
  name: string;
  before?: string;
  script: string;
  expect: {
    summary: { imported: number; present: number; skipped: number };
    warnings?: number;
    contains?: string[];
    absent?: string[];
  };
};

const IMPORT_CASES: ImportCase[] = [
  {
    name: "novel entries import, builtin-covered ones skip",
    script: [
      "IgnorePath '/swapfile'",
      "IgnorePath '/etc/machine-id'",
      "IgnorePath '/var/log/pacman.log'",
      "IgnorePath '*.pacsave'",
      "IgnoreFile /etc/group",
      "IgnorePackage --foreign neofetch",
    ].join("\n"),
    expect: {
      summary: { imported: 2, present: 0, skipped: 4 },
      contains: ["/swapfile", "neofetch"],
      absent: ["/etc/machine-id", "pacman.log", "*.pacsave", "/etc/group"],
    },
  },
  {
    name: "existing user entries count as present",
    before: "files: [/swapfile]\n",
    script: "IgnorePath '/swapfile'\nIgnorePath '/boot/vmlinuz-linux'\n",
    expect: {
      summary: { imported: 1, present: 1, skipped: 0 },
      contains: ["/swapfile", "/boot/vmlinuz-linux"],
    },
  },
  {
    name: "duplicates within the script dedupe",
    script: "IgnorePath /usr/bin/groupmems\nIgnorePath /usr/bin/groupmems\n",
    expect: {
      summary: { imported: 1, present: 1, skipped: 0 },
      contains: ["/usr/bin/groupmems"],
    },
  },
  {
    name: "warnings surface but entries still import",
    script: "IgnorePath '/etc/*-'\nFooBar baz\n",
    expect: {
      summary: { imported: 1, present: 0, skipped: 0 },
      warnings: 2,
      contains: ["/etc/*-"],
    },
  },
  {
    name: "subtree globs translate before writing",
    script: "IgnorePath '/etc/mullvad-vpn/*'\n",
    expect: {
      summary: { imported: 1, present: 0, skipped: 0 },
      contains: ["/etc/mullvad-vpn/**"],
    },
  },
];

const runImportCase = (c: ImportCase) => {
  if (c.before !== undefined) fs.writeFileSync(paths.etc.ignoreYaml, c.before);
  const s = runImport(c.script);
  expect({ imported: s.imported, present: s.present, skipped: s.skipped }).toEqual(
    c.expect.summary,
  );
  if (c.expect.warnings !== undefined) expect(s.warnings).toHaveLength(c.expect.warnings);
  const text = ignorefile.read().text;
  for (const sub of c.expect.contains ?? []) expect(text).toContain(sub);
  for (const sub of c.expect.absent ?? []) expect(text).not.toContain(sub);
};

for (const c of IMPORT_CASES) {
  test(`import: ${c.name}`, () => runImportCase(c));
}

test("import round-trips into an effective matcher", () => {
  runImport("IgnorePath '/var/*'\nIgnorePath '*.pacnew'\n");
  const m = ignore.compile(ignorefile.effective());
  expect(
    m.ignores({ type: "stray", id: "/var/lib/libvirt/x", field: "exists", expected: null, actual: null }),
  ).toBe(true);
  expect(m.prunes).toContain("/var");
});
