static const char* bc_db_schema =
  "CREATE TABLE IF NOT EXISTS file_metadata ("
  "  dev           INTEGER NOT NULL,"
  "  ino           INTEGER NOT NULL,"
  "  mtime_sec     INTEGER NOT NULL,"
  "  mtime_nsec    INTEGER NOT NULL,"
  "  ctime_sec     INTEGER NOT NULL,"
  "  ctime_nsec    INTEGER NOT NULL,"
  "  size          INTEGER NOT NULL,"
  "  sha256        BLOB    NOT NULL,"
  "  path          TEXT    NOT NULL,"
  "  last_seen_run INTEGER NOT NULL,"
  "  PRIMARY KEY (dev, ino)"
  ");"
  "CREATE TABLE IF NOT EXISTS mtrees ("
  "  pkg     TEXT    PRIMARY KEY,"
  "  version TEXT    NOT NULL,"
  "  mtime   INTEGER NOT NULL"
  ");"
  "CREATE TABLE IF NOT EXISTS mtree_entries ("
  "  pkg    TEXT    NOT NULL,"
  "  path   TEXT    NOT NULL,"
  "  type   INTEGER NOT NULL,"
  "  size   INTEGER,"
  "  mode   INTEGER,"
  "  uid    INTEGER,"
  "  gid    INTEGER,"
  "  mtime  INTEGER,"
  "  sha256 BLOB,"
  "  target TEXT,"
  "  PRIMARY KEY (pkg, path),"
  "  FOREIGN KEY (pkg) REFERENCES mtrees(pkg) ON DELETE CASCADE"
  ");"
  "CREATE TABLE IF NOT EXISTS meta_run ("
  "  run_id     INTEGER PRIMARY KEY AUTOINCREMENT,"
  "  started_at INTEGER NOT NULL,"
  "  action     TEXT    NOT NULL,"
  "  db_mtime   INTEGER,"
  "  elapsed    REAL"
  ");"
  "CREATE TABLE IF NOT EXISTS findings ("
  "  run_id     INTEGER NOT NULL,"
  "  kind       INTEGER NOT NULL,"
  "  path       TEXT    NOT NULL,"
  "  pkg        TEXT,"
  "  detail     TEXT,"
  "  created_at INTEGER NOT NULL"
  ");"
  "CREATE INDEX IF NOT EXISTS findings_run ON findings(run_id);";
